### ISSUE TITLE
dpms-off error

### ISSUE THREAD

**Issue by zz0rk** [lilydjwg/dpms-off#1]
All prerequisites fulfilled and built dpms-off successfully
When run ./dpms-off error

sudo apt install build-essential
sudo apt install libwlroots6
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
cargo build --release

~/Downloads/dpms-off-master/target/release$ ./dpms-off 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:52:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lilydjwg** [comment]
What Wayland compositor are you using? Could you post output of `wayland-info` command?

**Comment by zz0rk** [comment]
Hm... I don't have that command. I am running Debian 11 and I thought it uses Wayland. My apologies for the confusion.

**Comment by lilydjwg** [comment]
Install the `weston` package and run `weston-info`.

**Comment by zz0rk** [comment]
$ weston-info

*** Please use wayland-info instead
*** weston-info is deprecated and will be removed in a future version

interface: 'wl_drm', version: 2, name: 1
interface: 'wl_compositor', version: 4, name: 2
interface: 'wl_shm', version: 1, name: 3
	formats: 'XB4H'(0x48344258) 'AB4H'(0x48344241) 'XR4H'(0x48345258) 'AR4H'(0x48345241) 'XB30'(0x30334258) 'AB30'(0x30334241) 'XR30'(0x30335258) 'AR30'(0x30335241) RGB565 XRGB8888 ARGB8888
interface: 'wl_output', version: 2, name: 4
	x: 0, y: 0, scale: 1,
	physical_width: 280 mm, physical_height: 160 mm,
	make: 'BOE', model: '0x05f4',
	subpixel_orientation: unknown, output_transform: normal,
	mode:
		width: 1366 px, height: 768 px, refresh: 59.999 Hz,
		flags: current preferred
interface: 'zxdg_output_manager_v1', version: 3, name: 5
	xdg_output_v1
		output: 4
		name: 'eDP-1'
		description: 'Built-in display'
		logical_x: 0, logical_y: 0
		logical_width: 1366, logical_height: 768
interface: 'wl_data_device_manager', version: 3, name: 6
interface: 'zwp_primary_selection_device_manager_v1', version: 1, name: 7
interface: 'gtk_primary_selection_device_manager', version: 1, name: 8
interface: 'wl_subcompositor', version: 1, name: 9
interface: 'xdg_wm_base', version: 3, name: 10
interface: 'zxdg_shell_v6', version: 1, name: 11
interface: 'wl_shell', version: 1, name: 12
interface: 'gtk_shell1', version: 3, name: 13
interface: 'wp_viewporter', version: 1, name: 14
interface: 'zwp_pointer_gestures_v1', version: 1, name: 15
interface: 'zwp_tablet_manager_v2', version: 1, name: 16
interface: 'wl_seat', version: 5, name: 17
	name: seat0
	capabilities: pointer keyboard
	keyboard repeat rate: 33
	keyboard repeat delay: 500
interface: 'zwp_relative_pointer_manager_v1', version: 1, name: 18
interface: 'zwp_pointer_constraints_v1', version: 1, name: 19
interface: 'zxdg_exporter_v1', version: 1, name: 20
interface: 'zxdg_importer_v1', version: 1, name: 21
interface: 'zwp_linux_dmabuf_v1', version: 3, name: 22
	formats:
	'AR4H'(0x48345241), modifier: 0x00ffffffffffffff
	'XR4H'(0x48345258), modifier: 0x00ffffffffffffff
	'XB4H'(0x48344258), modifier: 0x00ffffffffffffff
	'AB4H'(0x48344241), modifier: 0x00ffffffffffffff
	'RG16'(0x36314752), modifier: 0x00ffffffffffffff
	'XR30'(0x30335258), modifier: 0x00ffffffffffffff
	'AR30'(0x30335241), modifier: 0x00ffffffffffffff
	'XR24'(0x34325258), modifier: 0x00ffffffffffffff
	'AR24'(0x34325241), modifier: 0x00ffffffffffffff
interface: 'zwp_keyboard_shortcuts_inhibit_manager_v1', version: 1, name: 23
interface: 'zwp_text_input_manager_v3', version: 1, name: 24
interface: 'gtk_text_input_manager', version: 1, name: 25

**Comment by lilydjwg** [comment]
You don't have the `zwlr_output_power_manager_v1` and `org_kde_kwin_idle` interfaces. That's why it doesn't work.

I'll make a clear error message.
